services:
  mysql:
    image: mysql:8.0
    container_name: shareday-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_pw
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app_pw
      TZ: Asia/Seoul
    # 기존에 다른 MySQL이 3306을 쓰고 있을 수 있으니 외부 포트는 3307로 피합니다.
    ports:
      - "3307:3306"
    volumes:
      - /volume1/docker/mysql/shareday-be/data:/var/lib/mysql
      - /volume1/docker/mysql/shareday-be/init:/docker-entrypoint-initdb.d:ro
#      - /volume1/docker/mysql/shareday-be/conf/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    restart: unless-stopped

  app:
    image: shareday-be:1.0.0
    container_name: shareday-be
    depends_on: [mysql]
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Seoul
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/app?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=utf8
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: app_pw
    volumes:
      - /volume1/docker/shareday-be/logs:/app/logs   # ← 폴더명이 log에 맞춤
      # - /volume1/docker/shareday-be/config:/app/config:ro  # 필요 시만
    restart: unless-stopped
