spring.application.name=shareday-be
spring.thymeleaf.cache=false
spring.resources.static-locations=classpath:/static/

# JWT ?? ? (??? ?????? ???? ?)
jwt.secret=7TtS#0$Mlnz9O8kD1A5wqD$4*Wk6VwQ&2R!Ls7fg

# JWT ?? ?? ?? (1?? = 3600000ms)
jwt.expiration=3600000
