name: CI

on:
  pull_request:
    branches: [ dev, main ]
    types: [opened, reopened, ready_for_review, synchronize]
  push:
    branches: [ dev ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

# 워크플로우 전체 권한 (리뷰어 요청 위해 필요)
permissions:
  contents: read
  pull-requests: write

jobs:
  # ✅ 빌드 & 테스트
  build-test:
    name: build-and-test
    runs-on: ubuntu-latest
    # push/PR 모두에서 실행
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build & Test
        run: ./gradlew clean build --stacktrace

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            **/build/reports/tests/**
            **/build/test-results/**
            **/build/reports/jacoco/**
